[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pragati-backend"
version = "0.1.0"
dependencies = [
    "Flask>=2.3",
    "firebase-admin",
    "google-generativeai"
]
